# Generated by Django 5.2.1 on 2025-05-23 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eq_contract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eqtransactions',
            name='contract',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='eq_contract.eqcontracts'),
            preserve_default=False,
        ),
    ]
