# Generated by Django 5.2.1 on 2025-05-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eq_contract', '0004_alter_eqtransactions_num_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eqcontracts',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
