# Generated by Django 5.2.1 on 2025-05-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eq_contract', '0006_eqcontracts_id_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eqcontracts',
            name='date_add',
            field=models.DateField(auto_now_add=True),
        ),
    ]
