# Generated by Django 5.2.1 on 2025-05-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='unp',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
